### ISSUE TITLE
datasets error

### ISSUE THREAD

**Issue by cpy0029** [HunterJ-Lin/WSOVOD#4]
AssertionError: Attribute 'dirname' in the metadata of 'voc_2007_trainval' cannot be set to a different value!
datasets/VOC2007 != /home/data/dataset/VOC2007

How do I modify this question? 
I have set export DETECTRON2_DATASETS=/home/data/dataset/

**Comment by cpy0029** [comment]
The above issue has been resolved, need to put export DETECTRON2_DATASETS=/home/data/dataset/ in the first line of .bashrc.

However, the following error has now occurred:
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint models/DRN-WSOD/resnet18_ws_model_120_d2.pkl not found!

I have already set up in the config file (in WSOVOD_WSR_18_DC5_1x.yaml): WEIGHTS: "/home/data/code/WSOVOD/weight/DRN-WSOD/resnet18_ws_model_120_d2.pkl"

**Comment by cpy0029** [comment]
The above issue has been resolved, need to put export DETECTRON2_DATASETS=/home/data/dataset/ in the first line of .bashrc.

However, I seem to be unable to find out how to modify the batch_size in the config. Could you please instruct me on how to change the batch_size?

**Comment by cpy0029** [comment]
The above issue has been resolved, need to put export DETECTRON2_DATASETS=/home/data/dataset/ in the first line of .bashrc.

**Comment by cpy0029** [comment]
Could you provide voc_text_embedding_single_prompt.pkl? The dimensions of this file after loading are 768.

  File "/home/data/code/WSOVOD/wsovod/modeling/class_heads/open_vocabulary_classifier.py", line 98, in forward
    class_weight = torch.cat(
                   ^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 512 for tensor number 1 in the list.

However, I am now encountering an error where the dimension of class_weight is 512, but the dimension of class_weight.new_zeros((self.weight_dim, 1)) is 768. Is there a mistake in generating the text embedding?

**Comment by HunterJ-Lin** [comment]
MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.WEIGHT_DIM should be aligned with the Clip text embed, I have modified the default Clip model used to generate class embed in generate_class_text_embedding.py.

**Comment by cpy0029** [comment]
> MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.WEIGHT_DIM should be aligned with the Clip text embed, I have modified the default Clip model used to generate class embed in generate_class_text_embedding.py.

Using generate_class_text_embedding.py to generate voc_text_embedding_single_prompt.pkl may still result in a unique mismatch problem.

**Comment by HunterJ-Lin** [comment]
> > MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.WEIGHT_DIM should be aligned with the Clip text embed, I have modified the default Clip model used to generate class embed in generate_class_text_embedding.py.
> 
> Using generate_class_text_embedding.py to generate voc_text_embedding_single_prompt.pkl may still result in a unique mismatch problem.

I have reviewed outputed the voc_text_embedding_single_prompt.py by the default CLIP model, i.e. ViT-B/32, showing that its shape be (20,512), could you providing more error log about your mismatch problem.

**Comment by cpy0029** [comment]
> > > MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.WEIGHT_DIM should be aligned with the Clip text embed, I have modified the default Clip model used to generate class embed in generate_class_text_embedding.py.
> > 
> > 
> > Using generate_class_text_embedding.py to generate voc_text_embedding_single_prompt.pkl may still result in a unique mismatch problem.
> 
> I have reviewed outputed the voc_text_embedding_single_prompt.py by the default CLIP model, i.e. ViT-B/32, showing that its shape be (20,512), could you providing more error log about your mismatch problem.

VOC is normal, but COCO still has this error

**Comment by cpy0029** [comment]
> > > > MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.WEIGHT_DIM should be aligned with the Clip text embed, I have modified the default Clip model used to generate class embed in generate_class_text_embedding.py.
> > > 
> > > 
> > > Using generate_class_text_embedding.py to generate voc_text_embedding_single_prompt.pkl may still result in a unique mismatch problem.
> > 
> > 
> > I have reviewed outputed the voc_text_embedding_single_prompt.py by the default CLIP model, i.e. ViT-B/32, showing that its shape be (20,512), could you providing more error log about your mismatch problem.
> 
> VOC is normal, but COCO still has this error

The issue has been resolved by using the latest files.
Thanks!
